name: Unit Test & Functional Test & E2E Test

on:
  push: ~
  pull_request: ~
  workflow_dispatch: ~

jobs:
  unit-tests:
    name: Unit & Functional Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha}}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache des dépendances Node
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install node modules
        id: installNodeModules
        shell: bash
        run: |
          npm install

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: unit-tests # Exécute après les tests unitaires

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha}}

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
